package nuevo_foro_fiuba

import grails.gorm.transactions.Transactional

@Transactional
class BootStrap {

    def usuarioService

    def init = { servletContext ->
      Usuario usuario = usuarioService.crearUsuario ("Mariano", "Martin", "mmartin")
      Usuario usuario2 = usuarioService.crearUsuario ("Rodrigo", "Aparicio", "raparicio")
      usuario2.save(failOnError:true)
      Usuario usuario3 = usuarioService.crearUsuario ("German", "Rotili", "grotili")
      Materia materia = new Materia ('Matematica discreta', 'Esto es mate discreta')
      materia.save(failOnError:true)
      Materia materia2 = new Materia ('Analisis II', 'Esto es analisis II')
      materia2.save(failOnError:true)
      Materia materia3 = new Materia ('Fisica II', 'Esto es fisica II')
      materia3.save(failOnError:true)
      Profesor profesor = new Profesor ('Acero')
      profesor.save(failOnError:true)
      Profesor profesor2 = new Profesor ('Sirne')
      profesor2.save(failOnError:true)
      Catedra catedra = new Catedra (materia, profesor, 'DescripcionCatedra_')
      catedra.save(failOnError:true)
      Catedra catedra2 = new Catedra (materia2, profesor2, 'DescripcionCatedra2_')
      catedra2.save(failOnError:true)
      Catedra catedra3 = new Catedra (materia3, profesor, 'DescripcionCatedra3_')
      catedra3.save(failOnError:true)
      Cursada cursada = new Cursada (usuario, catedra)
      cursada.save(failOnError:true)
      usuario.agregarCursada(cursada)
      Publicacion publicacion = new Publicacion ('TextoPublicacion_', usuario, materia, catedra)
      publicacion.save(failOnError:true)
      Publicacion publicacion2 = new Publicacion ('TextoPublicacion_', usuario2, materia2, catedra2)
      publicacion2.save(failOnError:true)
      Comentario comentario = new Comentario ("Soy el usuario2", usuario2, publicacion, null)
      comentario.save(failOnError:true)
      Comentario comentario2 = new Comentario ("Soy el usuario2 otra vez", usuario2, null, comentario)
      comentario2.save(failOnError:true)
      publicacion.agregarComentario(comentario)
      comentario.agregarComentario(comentario2)
      Cursada cursada2 = new Cursada (usuario, catedra2)
      cursada2.save(failOnError:true)
      usuario.agregarCursada(cursada2)
      Cursada cursada3 = new Cursada (usuario2, catedra3)
      cursada3.save(failOnError:true)
      usuario2.agregarCursada(cursada3)
      Puntaje puntaje = new Puntaje (Puntaje.TipoPuntaje.ME_GUSTA, 3)
      Calificacion calificacion = new Calificacion (usuario2, puntaje, publicacion, null)
      calificacion.save(failOnError:true)
      publicacion.agregarCalificacion(calificacion)
      Archivo archivo = new Archivo("Nombre","C:/Users/Mariano/Desktop/GitHub/Historias de usuario hechas.txt")
      archivo.save(failOnError:true)
      MensajePrivado mensaje = new MensajePrivado("Mensaje", null, archivo)
      mensaje.save(failOnError:true)
      InformacionMensajeUsuario info1 = new InformacionMensajeUsuario(usuario,usuario3, mensaje, InformacionMensajeUsuario.RolUsuarioMensaje.RECEPTOR)
      info1.save(failOnError:true)
      usuario.guardarMensaje(info1)
      usuario.save(failOnError:true)
      InformacionMensajeUsuario info2 = new InformacionMensajeUsuario(usuario3,usuario, mensaje, InformacionMensajeUsuario.RolUsuarioMensaje.EMISOR)
      info2.save(failOnError:true)
      usuario3.guardarMensaje(info2)
      usuario3.save(failOnError:true)
      Opcion opcion1 = new Opcion ("Buena")
      opcion1.save(failOnError:true)
      Opcion opcion2 = new Opcion ("Mala")
      opcion2.save(failOnError:true)
      Opcion opcion3 = new Opcion ("Me es indiferente")
      opcion3.save(failOnError:true)
      Encuesta encuesta = new Encuesta ("Qué opinan de la cátedra?", [opcion1,opcion2,opcion3].toSet())
      encuesta.save(failOnError:true)
      publicacion.agregarEncuesta(encuesta)
    }
    def destroy = {
    }
}
